name: mercado_justo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_modular: ^4.5.0
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  material_design_icons_flutter: ^5.0.6595
  url_launcher: ^6.0.20
  dio: ^4.0.6
  build_runner: ^2.1.8
  firebase_auth: ^3.3.13
  mask_text_input_formatter: ^2.3.0
  firebase_core: ^1.14.0
  google_sign_in: ^5.3.0
  cached_network_image: ^3.2.0
  geolocator: ^8.2.0
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2+1
  path_provider: ^2.0.9
  flutter_barcode_scanner: ^2.0.0
  google_maps_flutter: ^2.1.8
  currency_text_input_formatter: ^2.1.7
  cpf_cnpj_validator: ^2.0.0
  clipboard: ^0.1.3
  share_plus: ^4.5.3
  google_mobile_ads: ^2.0.0
  flutter_screenutil: ^5.6.0
  flutter_html: ^2.2.1
  flutter_launcher_icons: ^0.11.0
  # mercado_pago_mobile_checkout: ^0.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.5+2
  modular_test: ^1.0.1+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_2.png"
  min_sdk_android: 21 
  adaptive_icon_background: "#000000"

scripts:
  build: "flutter packages run build_runner build"
  watch: "flutter packages run build_runner watch"
  delete: "flutter packages run build_runner build --delete-conflicting-outputs"


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/img/products/
    - assets/img/markets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
